### ISSUE TITLE
Не правильная работа модуля Яндекс.Маркет

### ISSUE THREAD

**Issue by asnigma** [yandex-money/yandex-money-ycms-opencart3#26]
Версия модуля  1.1.3
Версия OpenCart 3.0.2.0 (rs.3)

При попытке загрузить прайс лист в системе Яндекс.Маркет выдается ошибка, что не соответствует требованиям формата YMC, XMl. 
При проверки  вылезла такая ошибка 

> Fatal error: Cannot use 'Object' as class name as it is reserved in /var/www/........../catalog/model/extension/payment/yandex_money/YandexMarket/Object.php on line 5

Рекомендация переименовать имя класса

**Comment by ostulov** [comment]
Благодарю, исправим.

**Comment by yangzong18** [comment]
how do I get the auth-token?

**Comment by ostulov** [comment]
> how do I get the auth-token?

Please, provide us with more information about your actions and settings of module. Send an e-mail to cms@yamoney.ru with details.

**Comment by ostulov** [comment]
Исправление сделано в версии 1.2.3
