### ISSUE TITLE
Как добавить sales_notes?

### ISSUE THREAD

**Issue by JuliaPikachuuu** [yandex-money/yandex-money-ycms-opencart3#30]
Добрый день!
Подскажите, пожалуйста, данный модуль обладает функцией добавления sales_notes?
Если нет, то подскажите, пожалуйста, в какой папке хранится файл в который можно добавить sales_notes?

**Comment by ostulov** [comment]
Добрый день!

Вы можете добавить sales_notes через дополнительные условия:
http://prntscr.com/lzqdh8

**Comment by JuliaPikachuuu** [comment]
Спасибо большое за такой быстрый ответ!
