### ISSUE TITLE
Ошибка выставления счета в действиях списка заказов

### ISSUE THREAD

**Issue by kappa08021982** [yandex-money/yandex-money-ycms-opencart3#35]
При нажатии на кнопку появляется ошибка:
![image](https://user-images.githubusercontent.com/39260157/52260129-f2d4e980-2946-11e9-8010-5429c98ddbcf.png)

**Comment by ostulov** [comment]
Добрый день!

Благодарю за обращение, подготовим исправление для данной ошибки.
До момента выхода исправления Вы можете выставлять счета из личного кабинета Яндекс.Кассы со страницы https://kassa.yandex.ru/my/invoice
