### ISSUE TITLE
Нет возможности оплаты банковской картой.

### ISSUE THREAD

**Issue by real-prospect** [yandex-money/yandex-money-ycms-opencart3#5]
При переходе к оплате банковской картой платеж идет через Яндекс деньги.

**Comment by kappa08021982** [comment]
Поддерживаю. При использовании версии 1.0.6 переход при использовании оплаты через Яндекс.Денеги и выборе оплаты картой переход идет в кошелек яндекс.денег.

**Comment by ostulov** [comment]
Добрый день!

Мы исправим данный баг в ближайшей версии модуля.
Благодарю за обращение!

**Comment by ostulov** [comment]
Исправлено в версии v1.0.8 от 21.05.2018
