### ISSUE TITLE
Пишет код не найден ft_frame theme

### ISSUE THREAD

**Issue by Hkr32** [yandex-money/yandex-money-ycms-opencart3#52]
ERROR: CODE NOT FOUND!
FILE: catalog/view/theme/ft_frame/template/common/footer.twig
CODE: <p>{{ powered }}</p>
MOD: Y.CMS for Opencart 3.x

ERROR: CODE NOT FOUND!
FILE: catalog/view/theme/ft_frame/template/product/product.twig
CODE: <div id="product"> {% if options %}
MOD: Y.CMS for Opencart 3.x

**Comment by ostulov** [comment]
Добрый день!

Чтобы код модификатора применился без проблем, привяжите выполнение кода к другим элементам, которые есть в Ваших файлах темы. Файл модификатора - https://github.com/yandex-money/yandex-money-ycms-opencart3/blob/master/src/install.xml

Первая часть кода нужна для опции в модуле "Показывать ссылку на сайт Кассы".
Вторая - для добавления блока «Заплатить по частям» в карточки товаров.
