### ISSUE TITLE
Помогите при оплате яндекс деньги создаются Пропавшие заказы

### ISSUE THREAD

**Issue by nomusic44989** [yandex-money/yandex-money-ycms-opencart3#66]
Добрый день. помогите пожалуйста. При оплате яндекс деньги не меняет статус заказа ( order_status_id = 0)

**Comment by ostulov** [comment]
Добрый день!

В первую очередь необходимо проверить, что правильно установлен адрес для уведомлений и модуль получает уведомление об успешной оплате.

**Comment by nomusic44989** [comment]
уведомление установлено на index.php?route=extension/payment/yandex_money/callback
а вот еще  такой вопрос должна ли вести запись в log что модуль получает ответ, запись не ведется не какой

**Comment by ostulov** [comment]
При получении уведомления от Яндекс.Кассы и Яндекс.Денег в логе модуля появляется запись об этом. Уточните у техподдержки платежного сервиса подробности отправки уведомления, успешно ли оно доходит?

**Comment by nomusic44989** [comment]
Спасибо большое
